name: Terraform Infrastructure CI/CD
 
on:
    push: 
         branches:
              - main

jobs: 
    build:
     runs-on: ubuntu-latest

     defaults:
          run:
          working_directory: terraform

     steps:
         - name: Checkout Repo
           uses: actions/checkout@v2

         - name: Setup Terraform
           uses: hashicorp/setup-terraform@v1
           env:
             github-token: ${{ secrets.GITHUB_TOEKN }}
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region: ${{ secrets.AWS_REGION }}

         - name: Terraform Init
           run: terraform init
         - name: Terraform validate
           run: terraform validate
         - name: Terraform Plan
           run: terraform plan
         - name: Terraform Apply
           run: terraform apply -auto-approve 